name: core_ui
description: Shared UI components and themes for food_hit apps
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1

flutter:
  uses-material-design: true
