name: core_utils
description: Shared utility functions for food_hit apps
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
